export const moons = [
    {
        'id' : 'earth-moons',
        'title' : `Earth's Moon`,
        'celestial_bodies' : 'moons',
        'description' : `Our only natural satellite is a stabilizing force that makes the planet a more pleasant place for life.`,
        'moons' : 'Luna',
        'data' : `The brightest and largest object in our night sky, the Moon makes Earth a more livable planet by moderating our home planet's wobble on its axis, leading to a relatively stable climate. It also causes tides, creating a rhythm that has guided humans for thousands of years. The Moon was likely formed after a Mars-sized body collided with Earth.`,
        'imageURL' : 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1672183068/solarSystem/emoon_480x360_moonsbydest_yibeii.jpg',
    },
    {
        'id' : 'mars-moons',
        'title' : `Mars Moon`,
        'celestial_bodies' : 'moons',
        'description' : `Two tiny moons orbit the Red Planet. One, Phobos, is slowly being torn apart by Mars.`,
        'moons' : 'Phobos, Deimos',
        'data' : `Asaph Hall was about to give up his frustrating search for a Martian moon one August night in 1877, but his wife Angelina urged him on. He discovered Deimos the next night, and Phobos six nights after that. Ninety-four years later, NASA's Mariner 9 spacecraft got a much better look at the two moons from its orbit around Mars. The dominant feature on Phobos, it found, was a crater six miles (10 kilometers) wide – nearly half the width of the moon itself. It was given Angelina's maiden name: Stickney.`,
        'imageURL' : 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1672193999/solarSystem/mars_480x360_moonsbydest_px5vgl.jpg',
    },
    {
        'id' : 'jupiter-moons',
        'title' : `Jupiter Moon`,
        'celestial_bodies' : 'moons',
        'description' : `Moons swarm around this giant world, including icy Europa with its hidden ocean.`,
        'moons' : 'Metis, Adrastea, Amaltea, Tebe, Io, Europa, Ganímedes,. Calisto, Temisto, Leda, Himalia, Lisitea, Elara, Dia, Carpo, S/2003 J 12, Euporia, S/2003 J 3, S/2003 J 18, Ortosia, Euante, Harpálice, Praxídice, Tione, S/2003 J 16, Yocasta, Mnemea, Hermipé, Telxínoe, Heliké, Ananqué, S/2003 J 15, Eurídome, Arce, Herse, Pasítea, S/2003 J 10, Caldona, Isonoé, Erínome, Calé, Aitné, Táigete, S/2003 J 9, Carmé, Espondé, Megaclite, S/2003 J 5, S/2003 J 19, S/2003 J 23, Cálice, Pasifae, Eukélade, S/2003 J 4, Sinope, Hegémone, Cilene, Aedea, Kore, Kallichore, Autónoe, Calírroe, S/2003 J 2, S/2010 J 1, S/2010 J 2, S/2011 J 1, S/2011 J 2, S/2016 J 1, S/ 2017 J 1',
        'data' : `Jupiter has 80 moons. Fifty-seven moons have been given official names by the International Astronomical Union (IAU). Another 23 moons are awaiting official names. There are many interesting moons orbiting the planet, but the ones of most scientific interest are the first four moons discovered beyond Earth – the Galilean satellites: Io, Europa, Ganymede, and Callisto.`,
        'imageURL' : 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1672194014/solarSystem/jupiter_480x360_moonsbydest_nro5sc.jpg',
    },
    {
        'id' : 'saturn-moons',
        'title' : `Saturn Moon`,
        'celestial_bodies' : 'moons',
        'description' : `Some moons of Saturn shape its beautiful rings. One is equal in size to a planet.`,
        'moons' : 'Aegir, Albiorix, Antea, Atlas, Bebhionn, Bergelmir, Bestla, Calipso, Daphne, Dione, Egeón, Encélado, Epimeteo, Erriap, Farbauti, Fenrir, Fornjot, Greip, Hati, Helena, Hiperión, Hyrrokkin, Jápeto, Ijiraq, Jano, Jarnsaxa, Kari, Kiviuq, Loge, Metone, Mimas, Mundilfari, Narvi, Paaliaq, Palene, Pan, Pandora, Febe, Polux, Prometeo, Rea, Siarnaq, Skadi, Skoll, Surtur, Suttung, Tarqeq, Tarvos, Telesto, Tetis, Thrym, Titán y Ymir.',
        'data' : `Saturn has 83 moons. Sixty-three moons are confirmed and named, and another 20 moons are awaiting confirmation of discovery and official naming by the International Astronomical Union (IAU). Saturn's moons range in size from larger than the planet Mercury – the giant moon Titan – to as small as a sports arena. The moons shape, contribute to, and also collect material from Saturn's rings and magnetosphere.`,
        'imageURL' : 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1672194027/solarSystem/saturn_480x360_moonsbydest_zuynpb.jpg',
    },
    {
        'id' : 'uranus-moons',
        'title' : `Uranus Moon`,
        'celestial_bodies' : 'moons',
        'description' : `Moons of this distant ice giant are named for great literature.`,
        'moons' : 'Cordelia, Ofelia, Bianca, Crésida, Desdémona, Julieta, Porcia, Rosalinda, Cupido, Belinda, Perdita, Puck, Mab, Miranda, Ariel, Umbriel, Titania, Oberón, Francisco, Calibán, Stefano, Trínculo, Sycorax, Margarita, Próspero, Setebos, Ferdinando',
        'data' : `“Sweet Moon," William Shakespeare wrote in "A Midsummer Night's Dream," "I thank thee for thy sunny beams; I thank thee, Moon, for shining now so bright." Centuries later, the moons of Uranus pay homage to the famous playwright. While most of the satellites orbiting other planets take their names from various mythologies, Uranus' moons are unique in being named for Shakespearean characters, along with a couple of the moons being named for characters from the works of Alexander Pope. `,
        'imageURL' : 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1672194041/solarSystem/uranus_480x360_moonsbydest_ejabab.jpg',
    },
    {
        'id' : 'neptune-moons',
        'title' : `Neptune Moon`,
        'celestial_bodies' : 'moons',
        'description' : `Icy Triton may be a captured world from the Kuiper Belt.`,
        'moons' : 'Triton, Proteus, Nereid, Larissa, Galatea, Despina, Thalassa, Naiad, Halimede, Neso, Sao, Laomedia, Psamathe, S/2004 N1',
        'data' : `We don't know if William Lassell had a celebratory beverage after he discovered Neptune's moon, Triton, but beer made the finding possible. Lassell was one of 19th century England's grand amateur astronomers, using the fortune he made in the brewery business to finance his telescopes. He spotted Triton on Oct. 10, 1846 – just 17 days after a Berlin observatory discovered Neptune. Scientists using powerful telescopes and spacecraft have since discovered a total of 14 moons orbiting this distant, giant world`,
        'imageURL' : 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1672194042/solarSystem/neptune_480x360_moonsbydest_mxl3cn.jpg',
    },
]