export const planets = [
    {
        'id': 'Mercury',
        'celestial_bodies' : 'planets',
        'nickName': 'Swift Planet',
        'description': `Mercury's surface resembles that of Earth's Moon, scarred by many impact craters resulting from collisions with meteoroids and comets.`,
        'imageURL': 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1671699578/solarSystem/5d35fc883a15e11a44a34973d446fd62_naf9ru.jpg',
        'background': 'background-mercury',
        'satellites' : `It doesn't have`,
        'orbital_velocity' : '47,8725 km/s',
        'diameter' : '4879,4 km',
        'radio' : '2 439.7 kilómetros',
        'mass' : '3,285 × 10^23kg',
        'volume' : '	6,083×10^10 km³',
        'gravity' : '3,7 m/s²​',
        'escape_velocity' : '4,25 km/s',
        'rotation_period' : '58,7 days',
        'sidereal_period' : '87d 23,23h',
        'synodic_period' : '115,88 days',
        'more_data' : `The smallest planet in our solar system and nearest to the Sun, Mercury is only slightly larger than Earth's Moon. From the surface of Mercury, the Sun would appear more than three times as large as it does when viewed from Earth, and the sunlight would be as much as seven times brighter. Despite its proximity to the Sun, Mercury is not the hottest planet in our solar system – that title belongs to nearby Venus, thanks to its dense atmosphere. Because of Mercury's elliptical – egg-shaped – orbit, and sluggish rotation, the Sun appears to rise briefly, set, and rise again from some parts of the planet's surface. The same thing happens in reverse at sunset.`
    },
    {
        'id': 'Venus',
        'celestial_bodies' : 'planets',
        'nickName': 'Morning and Evening Star',
        'description': 'Venus is the brightest object in the sky after the Sun and the Moon, and sometimes looks like a bright star in the morning or evening sky.',
        'imageURL': 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1671699540/solarSystem/627307fc797bedee91c8ccbaa48761a6_ovxdtq.jpg',
        'background': 'background-venus',
        'satellites' : `It doesn't have`,
        'orbital_velocity' : '35.02 km/s',
        'diameter' : '12 103,6 km',
        'radio' : '	6 051,8 km',
        'mass' : '4,869 × 10^24 kg',
        'volume' : '9,28x10^11 km³',
        'gravity' : '8,87 m/s²',
        'escape_velocity' : '10,36 km/s',
        'rotation_period' : '243,0187 days',
        'sidereal_period' : '224,701 days',
        'synodic_period' : '583,92 days',
        'more_data' : `Venus has a thick, toxic atmosphere filled with carbon dioxide and it’s perpetually shrouded in thick, yellowish clouds of sulfuric acid that trap heat, causing a runaway greenhouse effect. It’s the hottest planet in our solar system, even though Mercury is closer to the Sun. Surface temperatures on Venus are about 900 degrees Fahrenheit (475 degrees Celsius) – hot enough to melt lead. The surface is a rusty color and it’s peppered with intensely crunched mountains and thousands of large volcanoes. Scientists think it’s possible some volcanoes are still active. Venus has crushing air pressure at its surface – more than 90 times that of Earth – similar to the pressure you'd encounter a mile below the ocean on Earth. Another big difference from Earth – Venus rotates on its axis backward, compared to most of the other planets in the solar system. This means that, on Venus, the Sun rises in the west and sets in the east, opposite to what we experience on Earth. (It’s not the only planet in our solar system with such an oddball rotation – Uranus spins on its side.)`
    },
    {
        'id': 'Earth',
        'celestial_bodies' : 'planets',
        'nickName': 'Blue Planet',
        'description': 'Earth, our home planet, is a world unlike any other. The third planet from the sun, Earth is the only place in the known universe confirmed to host life.',
        'imageURL': 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1671699529/solarSystem/3fd4e0499203cb28e0aa7335afe27f84_ooewkb.jpg',
        'background': 'background-earth',
        'satellites' : 'Luna',
        'orbital_velocity' : '29,78 km/s',
        'diameter' : '12.742 km',
        'radio' : '6.371 km',
        'mass' : '5,9736 × 10^24 kg',
        'volume' : '1,08321×10^12 km³',
        'gravity' : '9,80665 m/s²',
        'escape_velocity' : '11,186 km/s',
        'rotation_period' : '0,99726968 days',
        'sidereal_period' : '365,256363004 days',
        'synodic_period' : '',
        'more_data' : `While Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface. Just slightly larger than nearby Venus, Earth is the biggest of the four planets closest to the Sun, all of which are made of rock and metal. The name Earth is at least 1,000 years old. All of the planets, except for Earth, were named after Greek and Roman gods and goddesses. However, the name Earth is a Germanic word, which simply means “the ground.”`
    },
    {
        'id': 'Mars',
        'celestial_bodies' : 'planets',
        'nickName': 'the Blue Planet',
        'description': 'Earth, our home planet, is a world unlike any other. The third planet from the sun, Earth is the only place in the known universe confirmed to host life.',
        'imageURL': 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1671699532/solarSystem/edefb9bd2e4f6112fbcc0de5812334d5_naj0a5.jpg',
        'background': 'background-mars',
        'satellites' : 'Fobos, Deimos',
        'orbital_velocity' : '24,077 km/s',
        'diameter' : '	6794,4 km',
        'radio' : '	3 389.50 kilómetros',
        'mass' : '	 6,4185 × 10^23 kg',
        'volume' : '1,6318 × 10^11 km³',
        'gravity' : '3,72076 m/s²',
        'escape_velocity' : '5,027 km/s',
        'rotation_period' : '24,6229 hs',
        'sidereal_period' : '686,971 days',
        'synodic_period' : '779,96 days',
        'more_data' : `Mars is no place for the faint-hearted. It’s dry, rocky, and bitter cold. The fourth planet from the Sun, Mars is one of Earth's two closest planetary neighbors (Venus is the other). Mars is one of the easiest planets to spot in the night sky – it looks like a bright red point of light. Despite being inhospitable to humans, robotic explorers – like NASA's new Perseverance rover – are serving as pathfinders to eventually get humans to the surface of the Red Planet.`
    },
    {
        'id': 'Jupiter',
        'celestial_bodies' : 'planets',
        'nickName': 'the Blue Planet',
        'description': 'Earth, our home planet, is a world unlike any other. The third planet from the sun, Earth is the only place in the known universe confirmed to host life.',
        'imageURL': 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1671699576/solarSystem/acc601e18f7305d1d76b257dea179f2b_ptg69b.jpg',
        'background': 'background-jupiter',
        'satellites' : 'Jupiter has 80 moons. The ones of most scientific interest are the first four moons discovered beyond Earth: Io, Europa, Ganymede, and Callisto.',
        'orbital_velocity' : '13,0697 km/s',
        'diameter' : '142 984 km',
        'radio' : '71 492 kilómetros',
        'mass' : '1,899×10^27 kg',
        'volume' : '1,4313 × 10^15 km³',
        'gravity' : '24.79 m/s²',
        'escape_velocity' : '59,54 km/s',
        'rotation_period' : '9 h 55 m 30 s',
        'sidereal_period' : '11 a 315 d 1,1 h ',
        'synodic_period' : '398,9 days',
        'more_data' : `Jupiter has a long history of surprising scientists – all the way back to 1610 when Galileo Galilei found the first moons beyond Earth. That discovery changed the way we see the universe. Fifth in line from the Sun, Jupiter is, by far, the largest planet in the solar system – more than twice as massive as all the other planets combined. Jupiter's familiar stripes and swirls are actually cold, windy clouds of ammonia and water, floating in an atmosphere of hydrogen and helium. Jupiter’s iconic Great Red Spot is a giant storm bigger than Earth that has raged for hundreds of years. One spacecraft – NASA's Juno orbiter – is currently exploring this giant world.`
    },
    {
        'id': 'Saturn',
        'celestial_bodies' : 'planets',
        'nickName': 'the Blue Planet',
        'description': 'Earth, our home planet, is a world unlike any other. The third planet from the sun, Earth is the only place in the known universe confirmed to host life.',
        'imageURL': 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1671699548/solarSystem/d65ca4ac6ba58ad5eef7a83243cb5aee_d8aphw.jpg',
        'background': 'background-saturn',
        'satellites' : `Saturn has 83 moons. Saturn's moons range in size from larger than the planet Mercury – the giant moon Titan – to as small as a sports arena.`,
        'orbital_velocity' : '9672,4 m/s',
        'diameter' : '120 536 km',
        'radio' : '58 232 kilómetros',
        'mass' : '	5,688×10^26 kg',
        'volume' : '8,27×10^23 m³',
        'gravity' : '10,44 m/s²',
        'escape_velocity' : '35 490 m/s',
        'rotation_period' : '10 h 33 m 38 s ',
        'sidereal_period' : '29 a 167 d 6,7 h ',
        'synodic_period' : '378,1 days',
        'more_data' : `Saturn is the sixth planet from the Sun and the second-largest planet in our solar system. Adorned with thousands of beautiful ringlets, Saturn is unique among the planets. It is not the only planet to have rings – made of chunks of ice and rock – but none are as spectacular or as complicated as Saturn's. Like fellow gas giant Jupiter, Saturn is a massive ball made mostly of hydrogen and helium.`
    },
    {
        'id': 'Uranus',
        'celestial_bodies' : 'planets',
        'nickName': 'the Blue Planet',
        'description': 'Earth, our home planet, is a world unlike any other. The third planet from the sun, Earth is the only place in the known universe confirmed to host life.',
        'imageURL': 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1671699601/solarSystem/60909db99bbb451b4ac103e660375c0b_cbqplu.jpg',
        'background': 'background-uranus',
        'satellites' : 'It has 27 known satellites and all have definite names. The most important are (from largest to smallest): Titania, Oberon, Umbriel, Ariel and Miranda.',
        'orbital_velocity' : '6,81 km/s',
        'diameter' : '51.118 km',
        'radio' : '25 362 kilómetros',
        'mass' : '8,686×10^25 kg',
        'volume' : '6,833×10^13 km³',
        'gravity' : '8,69 m/s²',
        'escape_velocity' : '21,3 km/s',
        'rotation_period' : '-17h 14m (retrograde motion)',
        'sidereal_period' : '30,799,095  days 84,323 326 years 42,718 solar days ​With a sidereal day of −0.718 33 days17 h 14 min 24 s 6',
        'synodic_period' : '369,66 days',
        'more_data' : `Uranus is the seventh planet from the Sun, and has the third-largest diameter in our solar system. It was the first planet found with the aid of a telescope, Uranus was discovered in 1781 by astronomer William Herschel, although he originally thought it was either a comet or a star. It was two years later that the object was universally accepted as a new planet, in part because of observations by astronomer Johann Elert Bode. Herschel tried unsuccessfully to name his discovery Georgium Sidus after King George III. Instead, the scientific community accepted Bode's suggestion to name it Uranus, the Greek god of the sky, as suggested by Bode.​`
    },
    {
        'id': 'Neptune',
        'celestial_bodies' : 'planets',
        'nickName': 'the Blue Planet',
        'description': 'Earth, our home planet, is a world unlike any other. The third planet from the sun, Earth is the only place in the known universe confirmed to host life.',
        'imageURL': 'https://res.cloudinary.com/dgcuq2caj/image/upload/v1671699606/solarSystem/e118e9bc0f39b7465b682fcd5ca882a5_yurkph.jpg',
        'background': 'background-neptune',
        'satellites' : `Neptune has fourteen known satellites. Triton, Proteus, Nereid, and the rest of Neptune's satellites can be classified into two groups: the inner and outer ones.`,
        'orbital_velocity' : '5,4778 km/s',
        'diameter' : '49.572 km',
        'radio' : '24 622 kilómetros',
        'mass' : '1,024×10^26 kg',
        'volume' : '	6,254×10^13 km³',
        'gravity' : '11,15 m/s²',
        'escape_velocity' : '23,71 km/s',
        'rotation_period' : '0,671 days ',
        'sidereal_period' : '60190 days',
        'synodic_period' : '367,5 days',
        'more_data' : `Dark, cold, and whipped by supersonic winds, ice giant Neptune is the eighth and most distant planet in our solar system. More than 30 times as far from the Sun as Earth, Neptune is the only planet in our solar system not visible to the naked eye and the first predicted by mathematics before its discovery. In 2011 Neptune completed its first 165-year orbit since its discovery in 1846. NASA's Voyager 2 is the only spacecraft to have visited Neptune up close. It flew past in 1989 on its way out of the solar system.`
    },
]